# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
  LEANIX_API_TOKEN: ${{ LEANIX_API_TOKEN }}
  LEANIX_SUBDOMAIN: ${{ LEANIX_SUBDOMAIN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-python-script-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Run Python script
        run: uv run python main.py
  
  
        # This workflow contains a single job called "greet"
  # greet:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
    # Runs a single command using the runners shell
    # - name: Send greeting
      # run: echo "Hello ${{ inputs.name }}"
