# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

env:
  LEANIX_API_TOKEN: ${{ secrets.LEANIX_API_TOKEN }}
  LEANIX_SUBDOMAIN: ${{ secrets.LEANIX_SUBDOMAIN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-python-script-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
          
      - name: Check DNS resolution
        run: ping -c 4 demo-us.leanix.net

      - name: Run Python script
        run: uv run python main.py

        
